#!/bin/bash
export CD=`pwd`
if [ ! -f jdk-lin/lib/modules ]; then
  cd jdk-lin/lib
  echo "n" | unzip -o modules.zip
  cd $CD
fi
cd cdest/src-lin
xterm -T Scorer -fa "monospace" -fs 14 -fg black -bg white -e "java -jar cdx-contest.jar" &
